name: Build Booking-Frontend

on:
  push:
    branches:
    - main
  
jobs:
  publish:
   runs-on: ubuntu-latest

   steps:
   - uses: actions/checkout@v4

   - name: Login Docker Hub
     uses: docker/login-action@v3
     with:
       username: 43r63w
       password: ${{ secrets.DOCKER_PASSWORD }}
       
   - name: Docker Build
     uses: docker/build-push-action@v6
     with:
       context: .
       file: ./Dockerfile
       push: true
       tags: 43r63w/booking-frontent:dev
      
    

  
    
